POST http://localhost:3333/avicultores
Content-Type: application/json

{
    "nome": "Jogimar",
    "email": "jogimar@ave",
    "senha": "123"
}

###
GET http://localhost:3333/avicultores


###

PUT http://localhost:3333/avicultores/7
Content-Type: application/json

{
    "nome": "jorge agricola",
    "email": "jorge@ave",
    "senha": "12345"
}


###


DELETE http://localhost:3333/avicultores/1

