POST https://fpeso.onrender.com/avicultores
Content-Type: application/json

{
    "nome": "Carlos Souza",
    "email": "jorge@ave",
    "senha": "123"
}

###
GET https://fpeso.onrender.com/avicultores


###

PUT https://fpeso.onrender.com/avicultores/3
Content-Type: application/json

{
    "nome": "Carlos Souza",
    "email": "jorge@ave",
    "senha": "123"
}


###


DELETE https://fpeso.onrender.com/avicultores/6

