POST http://localhost:3333/avicultores
Content-Type: application/json

{
    "nome": "jorge da silva",
    "email": "jorge@ave",
    "senha": "123"
}

###

GET http://localhost:3333/avicultores


###

PUT http://localhost:3333/avicultores/1
Content-Type: application/json

{
    "nome": "jorge",
    "email": "jorge@ave",
    "senha": "1234"
}


###


DELETE http://localhost:3333/avicultores/1

